hash-format = "sha256"

[[files]]
file = "kubejs/README.txt"
hash = "989f3737ae4621b8ff6730bce4cbeeee756921e7e510e0c281c8a350501d98af"

[[files]]
file = "kubejs/assets/ponderjs_generated/lang/en_us.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "kubejs/client_scripts/example.js"
hash = "152019ed6e0410a82805a95ea10f1ad1a17beaf2b50864d89b8fa9d172129ac7"

[[files]]
file = "kubejs/config/client.properties"
hash = "8880aebdab51c9af5080fdc70c7fd1511f8559cfb1396904d80884244d9ecfb1"

[[files]]
file = "kubejs/config/common.properties"
hash = "c4bb70419f70e289edf108d144c3a5bb2822d1912632b3095fe24a37001fd838"

[[files]]
file = "kubejs/server_scripts/example.js"
hash = "a19b7c81a150bd965b153ded9c45ee7649eaad9e10d0a5ec1d662e7b15ceadb2"

[[files]]
file = "kubejs/startup_scripts/example.js"
hash = "395c96d3ddd178821db851f387e91560e606ea752177f66d2016f12bd0542b8f"

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "320e80999788a7c3b40ea0a8d0b14251b04f29baf71d217b2dcb432c1964d6dd"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "9e2c643198b995c754f1ad73518d241d879c7e84c9c129f67f8ce0587444c33d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "45d8570e9c13f5265d9d833ba2431e982ab9cf2760e86c6d5fd62dd3c092e18c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2492a7266fab4c2ff411612180974b98510afb66a18e640f4de63ad615dd1e9e"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "2ea3d87ffc2806e4bcb6ee9f5a35bdb4588b29030aba235dc7616d1833349d5b"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie-reloaded.pw.toml"
hash = "3702c3e7708f3d0686ede91c8368afbba1f80c1fd1db12d594a090c050996ace"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "06d9fc289964f42dfad761ff34dc7c2f09bb7dde3d8fc54954ad01f15c8714ed"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "9370fd82df230e26ca0f763395094a34b7a5a27eaec9b117d8ed736eb911fbfb"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "244f3cd7c2c8d676926bf8b7b7fcbee398caf99e849acdef037e105cafe42f50"
metafile = true

[[files]]
file = "mods/better-climbing.pw.toml"
hash = "2f0c572f52bd5508491258b40a1d18e3b5c93dfba89848d09ca68d43e0d3a8ee"
metafile = true

[[files]]
file = "mods/better-than-mending.pw.toml"
hash = "3ec39275606ec3fa45f7681ebac003c5cab962e77de1cf60d8a241639c736df2"
metafile = true

[[files]]
file = "mods/boat-break-fix.pw.toml"
hash = "f60a63c3251ebf33f6636e5fd773f281d3f09b3a273e346b1d2547cc0c67559b"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "e5739bf8e8668a5d94ae545f7ddabcffcdfec64b0e72d7d2d88d8f64f480977e"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "3b45878fbe0e15944f9d4c159741548debf4d775fd9e2f9992dcd1719c08b3da"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "07243121a8dde6746c46a5b96748abacec5d2da210f86d887daebb2d77922945"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "a952fb0d69dd033d3577501d2a0b3f0e4c013fa8b5b06a66a0f22eff8df5066d"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "329c2abe7b738559e19cad999d00a6f11cdf4a501a3c8676e26c9f543b033fcc"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e00fc109714e08b5ec2f5d74574eab80c9df8090d33e0d2fdeeeeb93df0c09b1"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "492359a6ce93fbf09eb6e1d20b761a5538fe9197e7d129949234d83b87e06bc1"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "6d791ef916287123f72c518b7b57a952ca25171542fb42393ffc48cd11cf17a4"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e7513fdc9b93652c928a5af59e9dc6a5b21dfe5200fe78883a6fa56d3cdefa1f"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "479b3a0a2e60138458a136bf176e84131646419b20fcaade540c948183d1d351"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "17d588c49f6c3bf2ad659c6d3fe073704a6e15c34bf69f70109a6b762e6ea0c3"
metafile = true

[[files]]
file = "mods/cosmetic-armor-fabric.pw.toml"
hash = "df4a2abec8e59fbce59a7ebbfdb26b840ed397432b037bce3e3e89609dc35cb3"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "aaef8c4a53f5488669468be5943621a5edb10566fb7d99c046b32edcf5dfb779"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
hash = "22188a09430d062b7c2e11447e324dda9d7b43a7a76529809065d7b818fa8b5c"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "c9297ce4f2d18b77e8ce81e94796f8b7e793f59f319cc574271e6e16980e23d1"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "7e310e12b5d5a2225025c90d4f5f1ad613581b3219bab49bc2b09bcd0670272f"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "4463005ad6ae41db2bf707952d6945297f48601a42ec8b6cac8aef09d653ffd2"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "a372da9cf25c8f7dd008bb210ba3616efa0a43c018b086065f3c3d0dc1e14bfc"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7abb69378bbeb4e07a6573f5c3ec8c362b1a14c3a70f67a22a57e844547d7cd2"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "ec2f847977196cfdbde04c23cb9d0389ef86b7b2276397b4bcf5e0b068280c96"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "49b988bf9af6cc2138aeba46e121c3865680cdf125d74af0c47466be9db5fa12"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "9ebf8104902092de2c078a9a4ea75eef96f1aabf086ecd127f69be63ae0a049d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b64a246a2066d6b8eb1cd7b9ab0e306412275ee2b3fae33ac5958c89b7f89f86"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "58bbea0798272c03012a8e3df88671a509d371331bd5f193b9fe36e644ffbfc7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c784cee4a8eed3f2b36172b8c5a119a62a28880d15e7f169947c935bf3bf4bb3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
hash = "9470fb9435b56597681a290a14707e527930456cf89fbce20c5196c72fc31252"
metafile = true

[[files]]
file = "mods/fastboot.pw.toml"
hash = "ed29698f8fe776f73fdb5e3ecf5ad77e2079f4d044adb0a04ee6d7df46ae9fbe"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "c344531240115caf4389148fd9ebe51731aa329cec5e9794a046e7050dae01ea"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "f0e7773218c4987d6f77c5f934e39848ca7af39d39f953f3d8f5a2c6d3efbbea"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c4c0793a0ff78953b53c6c592a4d178e99ef55406fc042ba67088bb8e039ed8d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4b17a3727e15bf347ba1ccbce06cbb787aa6236eafcb9c1a3ee126b1b8efd890"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
hash = "085b3c9833823b12799c665c24b48cd45cc505d416f58f652cca028e52ebbea9"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/iris-flywheel-compat.pw.toml"
hash = "847552c175b3b4c35e8106a75dbd1243b530487105871650fa7cbb52c2418b3a"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "bc64bb0f72acc944a8f6fd48e6147c698efd0456d6c63c27847bcaa896addd84"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
hash = "dd8a68293c82c888f01d4972ce764567e5af92c9641485fa17ba57b336e2da8e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "910fa36384741dbc199805f0afde8f5ef06940d1a74d1d737b7bc1048c58916f"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "242c3f3368eb9a3b1c583b8295ed7bf016b9fa649d44897660112f06886da960"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "789d382695029e664f45314b7c3d915dfb8baa82ef62a745ae3acb8b43559e3f"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "8d77fc83397ae9cf531f1fd1efca231e2f7698eb95444646a896e0790769dd4e"
metafile = true

[[files]]
file = "mods/konkrete-fabric.pw.toml"
hash = "34f9d95129ee85e65fb0c4c982b76c247bb11b59ca5bf50a84dd5daae33c51f6"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "8e3536092375aecb58eff2d81714fab7a3272375c9e6e19481ea500e6fbd9726"
metafile = true

[[files]]
file = "mods/leaky.pw.toml"
hash = "942eac0139c78d7c696c380f06c191ebcb9e01333eb0c5309a0dabd635247bb5"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
hash = "efec13373f18d1ca1265d84165bfbebdb8fb9c6cde8b8762819e84523b54e484"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "65e3b65aefe602f1c02d6216cfade41b2f2c06d5e7f29f3058c09cd12b966315"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "302e1ed3744ed7c21554cedc6d418d658faadc52c3fff942ba091a63acd2390c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "39d1aa66bf641027827a4bfcfe2c088ad6506405b0ff603fd65b1a9828d40c94"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "fed1e9c3ccc41302345e408bc4709d758c76de7385685460bb4209d41051e909"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
hash = "640c25efd97478f3b3b85d3402f101a2792c2c5dc2ad317189af228cb0054ac2"
metafile = true

[[files]]
file = "mods/lootr-fabric.pw.toml"
hash = "e7f748c45bab5a2d9c6c34d99703b9c8aa09e0c5e8069938cad9de693a9965e1"
metafile = true

[[files]]
file = "mods/memory-settings.pw.toml"
hash = "44df966bf9a3fd7022658665a6f1b01463232a451fdafdb22fbc08c495e2b76a"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "7b05b774f6fa69d4411c807f775285b6a46270acee5320aefac1c8e523892420"
metafile = true

[[files]]
file = "mods/mobtimizations.pw.toml"
hash = "a06d3c4d3e5963e97183c930124b25c82c5a04de93086f3a60c12d36a38b39a1"
metafile = true

[[files]]
file = "mods/model-gap-fix.pw.toml"
hash = "bf637761441cee7d1e7a2dd33c40079e7bbced018308a3ce223b6267816e60ba"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eb51c512ef2118c0aa99b718eff309741d98fde004a82f04a0e1fe599a240fa1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "1b4f637283c0c4e87d642641338dee78b0357b97fbc62fe69911cee8d0b557dc"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "020c457eee3a752be52370413f066cd0591bf992bae127b20ea04522b394a60e"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "5771c993ba18928e085af5d3ce1a20ee6b9488b8eb39507ed2d0a215777d69ae"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "6fab924e164f085a461460ad65dc048b528693137ddbc8e3b66667b68305cf54"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "41ed20cf88545759dcfd414c85b26d156eab8458c77f91be745deb540a3e45b0"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "91a34cb72ff22aaf1e12d1741782b73af9ad179255d9156b7c2c7a5f878ba1ce"
metafile = true

[[files]]
file = "mods/ponder.pw.toml"
hash = "f3dd8e053f22a26dcd6b1b203dc271ea4209ad35b0ae7c85b2bc002851797f5f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "ead2bfc6e6fa3d1f1d82a7f4968ab2c8a712866d635d1875f02936f9ad8aef02"
metafile = true

[[files]]
file = "mods/recipe-essentials-forge-fabric.pw.toml"
hash = "efcd3236fecc9e8041dea52989056588084521dafa8fb5cb1e47e4fdd69117e9"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "ac6f4641abc245146d5c56aa60b1131fb9d7d42ef43e675674b5fe7c30183394"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "bbe785207a0f25eddd5dae720b1bf482276cc792abb6386a928138d4a66cdd1a"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "98739e44d0a6e97c0776861a551cf689d9190a215640210007dd28d3edad9107"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "a3fd3c635d098e4479f6a5f35efbe8e3eaab7848c649af38049f5d52b6a49530"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "62d685e001957b2f677675df77e3d96be4ba9ce28cd19b286dc7b386a5b472b0"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "de0af6aaa8f6db933427c1bb67e07477024ad558c98b850c17a91283df7c5576"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "f99dacae134534a8ee4abbe14d02749e2028a25a00b9f87b4c46543e9c66f9f0"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "d5ed51699dd5358cabc504b6a553b290fd6578c9926ab14f29e14786d43b6b84"
metafile = true

[[files]]
file = "mods/starter-kit.pw.toml"
hash = "77a9d81c6cb8e4ed4440de7ab75cdc3417359e9ab56f8a7e5dde292032c2ecef"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "b45567da0b3a992bc7e80a447d57709b4afce4e0d52adeb0d9495f84a2052ef2"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "2303d834f326e3c45b0896aedf6299d8463a4e06ca2abca7d4008dd107fff34b"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "d9bfec2cf36b6bae2d85a1136560e047ab8ce1b0e9798e7b6be5d0670f65fb55"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "46d1b4a4a259be641ebf62692d2d5da5fe03098b94f125661d449d495fa2e167"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "bd1dc13316e2aa9b56c89e7e974057f8da8d6bbfe707ba4210109fc612b782e3"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
hash = "48c5a8213925efd652a9e13f40116d53e0516e9147b27d6d0e0ae8cf68f83f6d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "44e64dbb7f95c2ee2caf437dc9fe0755176badc19f4453a78291dd49746edd57"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "33d2f0583171ecd90451a5da5e8f827a352fa69d0cd55f51ff2f21845a1f81d9"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true
