name = "CNMC Geopol Fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c434ec405926f183e383d1c7a705c9e65810868576ca59543c177fd75f6a38f3"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
